// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_2_pw_keepalive.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "client_2_pw_keepalive.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace NetProto {
namespace C2PW {
class ClientKeepAliveReqDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<ClientKeepAliveReq> {
} _ClientKeepAliveReq_default_instance_;
class ClientKeepAliveRespDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<ClientKeepAliveResp> {
} _ClientKeepAliveResp_default_instance_;

namespace protobuf_client_5f2_5fpw_5fkeepalive_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientKeepAliveReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientKeepAliveReq, gs_id_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientKeepAliveResp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientKeepAliveResp, pw_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientKeepAliveResp, pw_time_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientKeepAliveResp, multiple_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(ClientKeepAliveReq)},
  { 6, -1, sizeof(ClientKeepAliveResp)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_ClientKeepAliveReq_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_ClientKeepAliveResp_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "client_2_pw_keepalive.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace

void TableStruct::Shutdown() {
  _ClientKeepAliveReq_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _ClientKeepAliveResp_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _ClientKeepAliveReq_default_instance_.DefaultConstruct();
  _ClientKeepAliveResp_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\033client_2_pw_keepalive.proto\022\rNetProto."
      "C2PW\"#\n\022ClientKeepAliveReq\022\r\n\005gs_id\030\001 \001("
      "\r\"G\n\023ClientKeepAliveResp\022\r\n\005pw_id\030\001 \001(\r\022"
      "\017\n\007pw_time\030\002 \001(\004\022\020\n\010multiple\030\003 \001(\rb\006prot"
      "o3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 162);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "client_2_pw_keepalive.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_client_5f2_5fpw_5fkeepalive_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClientKeepAliveReq::kGsIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClientKeepAliveReq::ClientKeepAliveReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_client_5f2_5fpw_5fkeepalive_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:NetProto.C2PW.ClientKeepAliveReq)
}
ClientKeepAliveReq::ClientKeepAliveReq(const ClientKeepAliveReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  gs_id_ = from.gs_id_;
  // @@protoc_insertion_point(copy_constructor:NetProto.C2PW.ClientKeepAliveReq)
}

void ClientKeepAliveReq::SharedCtor() {
  gs_id_ = 0u;
  _cached_size_ = 0;
}

ClientKeepAliveReq::~ClientKeepAliveReq() {
  // @@protoc_insertion_point(destructor:NetProto.C2PW.ClientKeepAliveReq)
  SharedDtor();
}

void ClientKeepAliveReq::SharedDtor() {
}

void ClientKeepAliveReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClientKeepAliveReq::descriptor() {
  protobuf_client_5f2_5fpw_5fkeepalive_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_client_5f2_5fpw_5fkeepalive_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ClientKeepAliveReq& ClientKeepAliveReq::default_instance() {
  protobuf_client_5f2_5fpw_5fkeepalive_2eproto::InitDefaults();
  return *internal_default_instance();
}

ClientKeepAliveReq* ClientKeepAliveReq::New(::google::protobuf::Arena* arena) const {
  ClientKeepAliveReq* n = new ClientKeepAliveReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ClientKeepAliveReq::Clear() {
// @@protoc_insertion_point(message_clear_start:NetProto.C2PW.ClientKeepAliveReq)
  gs_id_ = 0u;
}

bool ClientKeepAliveReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:NetProto.C2PW.ClientKeepAliveReq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 gs_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &gs_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:NetProto.C2PW.ClientKeepAliveReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:NetProto.C2PW.ClientKeepAliveReq)
  return false;
#undef DO_
}

void ClientKeepAliveReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:NetProto.C2PW.ClientKeepAliveReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 gs_id = 1;
  if (this->gs_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->gs_id(), output);
  }

  // @@protoc_insertion_point(serialize_end:NetProto.C2PW.ClientKeepAliveReq)
}

::google::protobuf::uint8* ClientKeepAliveReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:NetProto.C2PW.ClientKeepAliveReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 gs_id = 1;
  if (this->gs_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->gs_id(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:NetProto.C2PW.ClientKeepAliveReq)
  return target;
}

size_t ClientKeepAliveReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NetProto.C2PW.ClientKeepAliveReq)
  size_t total_size = 0;

  // uint32 gs_id = 1;
  if (this->gs_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->gs_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ClientKeepAliveReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:NetProto.C2PW.ClientKeepAliveReq)
  GOOGLE_DCHECK_NE(&from, this);
  const ClientKeepAliveReq* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ClientKeepAliveReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:NetProto.C2PW.ClientKeepAliveReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:NetProto.C2PW.ClientKeepAliveReq)
    MergeFrom(*source);
  }
}

void ClientKeepAliveReq::MergeFrom(const ClientKeepAliveReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NetProto.C2PW.ClientKeepAliveReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.gs_id() != 0) {
    set_gs_id(from.gs_id());
  }
}

void ClientKeepAliveReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:NetProto.C2PW.ClientKeepAliveReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClientKeepAliveReq::CopyFrom(const ClientKeepAliveReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NetProto.C2PW.ClientKeepAliveReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientKeepAliveReq::IsInitialized() const {
  return true;
}

void ClientKeepAliveReq::Swap(ClientKeepAliveReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClientKeepAliveReq::InternalSwap(ClientKeepAliveReq* other) {
  std::swap(gs_id_, other->gs_id_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ClientKeepAliveReq::GetMetadata() const {
  protobuf_client_5f2_5fpw_5fkeepalive_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_client_5f2_5fpw_5fkeepalive_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ClientKeepAliveReq

// uint32 gs_id = 1;
void ClientKeepAliveReq::clear_gs_id() {
  gs_id_ = 0u;
}
::google::protobuf::uint32 ClientKeepAliveReq::gs_id() const {
  // @@protoc_insertion_point(field_get:NetProto.C2PW.ClientKeepAliveReq.gs_id)
  return gs_id_;
}
void ClientKeepAliveReq::set_gs_id(::google::protobuf::uint32 value) {
  
  gs_id_ = value;
  // @@protoc_insertion_point(field_set:NetProto.C2PW.ClientKeepAliveReq.gs_id)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClientKeepAliveResp::kPwIdFieldNumber;
const int ClientKeepAliveResp::kPwTimeFieldNumber;
const int ClientKeepAliveResp::kMultipleFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClientKeepAliveResp::ClientKeepAliveResp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_client_5f2_5fpw_5fkeepalive_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:NetProto.C2PW.ClientKeepAliveResp)
}
ClientKeepAliveResp::ClientKeepAliveResp(const ClientKeepAliveResp& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&pw_time_, &from.pw_time_,
    reinterpret_cast<char*>(&multiple_) -
    reinterpret_cast<char*>(&pw_time_) + sizeof(multiple_));
  // @@protoc_insertion_point(copy_constructor:NetProto.C2PW.ClientKeepAliveResp)
}

void ClientKeepAliveResp::SharedCtor() {
  ::memset(&pw_time_, 0, reinterpret_cast<char*>(&multiple_) -
    reinterpret_cast<char*>(&pw_time_) + sizeof(multiple_));
  _cached_size_ = 0;
}

ClientKeepAliveResp::~ClientKeepAliveResp() {
  // @@protoc_insertion_point(destructor:NetProto.C2PW.ClientKeepAliveResp)
  SharedDtor();
}

void ClientKeepAliveResp::SharedDtor() {
}

void ClientKeepAliveResp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClientKeepAliveResp::descriptor() {
  protobuf_client_5f2_5fpw_5fkeepalive_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_client_5f2_5fpw_5fkeepalive_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ClientKeepAliveResp& ClientKeepAliveResp::default_instance() {
  protobuf_client_5f2_5fpw_5fkeepalive_2eproto::InitDefaults();
  return *internal_default_instance();
}

ClientKeepAliveResp* ClientKeepAliveResp::New(::google::protobuf::Arena* arena) const {
  ClientKeepAliveResp* n = new ClientKeepAliveResp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ClientKeepAliveResp::Clear() {
// @@protoc_insertion_point(message_clear_start:NetProto.C2PW.ClientKeepAliveResp)
  ::memset(&pw_time_, 0, reinterpret_cast<char*>(&multiple_) -
    reinterpret_cast<char*>(&pw_time_) + sizeof(multiple_));
}

bool ClientKeepAliveResp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:NetProto.C2PW.ClientKeepAliveResp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 pw_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &pw_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 pw_time = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &pw_time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 multiple = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &multiple_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:NetProto.C2PW.ClientKeepAliveResp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:NetProto.C2PW.ClientKeepAliveResp)
  return false;
#undef DO_
}

void ClientKeepAliveResp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:NetProto.C2PW.ClientKeepAliveResp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 pw_id = 1;
  if (this->pw_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->pw_id(), output);
  }

  // uint64 pw_time = 2;
  if (this->pw_time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->pw_time(), output);
  }

  // uint32 multiple = 3;
  if (this->multiple() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->multiple(), output);
  }

  // @@protoc_insertion_point(serialize_end:NetProto.C2PW.ClientKeepAliveResp)
}

::google::protobuf::uint8* ClientKeepAliveResp::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:NetProto.C2PW.ClientKeepAliveResp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 pw_id = 1;
  if (this->pw_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->pw_id(), target);
  }

  // uint64 pw_time = 2;
  if (this->pw_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->pw_time(), target);
  }

  // uint32 multiple = 3;
  if (this->multiple() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->multiple(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:NetProto.C2PW.ClientKeepAliveResp)
  return target;
}

size_t ClientKeepAliveResp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NetProto.C2PW.ClientKeepAliveResp)
  size_t total_size = 0;

  // uint64 pw_time = 2;
  if (this->pw_time() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->pw_time());
  }

  // uint32 pw_id = 1;
  if (this->pw_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->pw_id());
  }

  // uint32 multiple = 3;
  if (this->multiple() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->multiple());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ClientKeepAliveResp::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:NetProto.C2PW.ClientKeepAliveResp)
  GOOGLE_DCHECK_NE(&from, this);
  const ClientKeepAliveResp* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ClientKeepAliveResp>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:NetProto.C2PW.ClientKeepAliveResp)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:NetProto.C2PW.ClientKeepAliveResp)
    MergeFrom(*source);
  }
}

void ClientKeepAliveResp::MergeFrom(const ClientKeepAliveResp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NetProto.C2PW.ClientKeepAliveResp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.pw_time() != 0) {
    set_pw_time(from.pw_time());
  }
  if (from.pw_id() != 0) {
    set_pw_id(from.pw_id());
  }
  if (from.multiple() != 0) {
    set_multiple(from.multiple());
  }
}

void ClientKeepAliveResp::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:NetProto.C2PW.ClientKeepAliveResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClientKeepAliveResp::CopyFrom(const ClientKeepAliveResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NetProto.C2PW.ClientKeepAliveResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientKeepAliveResp::IsInitialized() const {
  return true;
}

void ClientKeepAliveResp::Swap(ClientKeepAliveResp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClientKeepAliveResp::InternalSwap(ClientKeepAliveResp* other) {
  std::swap(pw_time_, other->pw_time_);
  std::swap(pw_id_, other->pw_id_);
  std::swap(multiple_, other->multiple_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ClientKeepAliveResp::GetMetadata() const {
  protobuf_client_5f2_5fpw_5fkeepalive_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_client_5f2_5fpw_5fkeepalive_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ClientKeepAliveResp

// uint32 pw_id = 1;
void ClientKeepAliveResp::clear_pw_id() {
  pw_id_ = 0u;
}
::google::protobuf::uint32 ClientKeepAliveResp::pw_id() const {
  // @@protoc_insertion_point(field_get:NetProto.C2PW.ClientKeepAliveResp.pw_id)
  return pw_id_;
}
void ClientKeepAliveResp::set_pw_id(::google::protobuf::uint32 value) {
  
  pw_id_ = value;
  // @@protoc_insertion_point(field_set:NetProto.C2PW.ClientKeepAliveResp.pw_id)
}

// uint64 pw_time = 2;
void ClientKeepAliveResp::clear_pw_time() {
  pw_time_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 ClientKeepAliveResp::pw_time() const {
  // @@protoc_insertion_point(field_get:NetProto.C2PW.ClientKeepAliveResp.pw_time)
  return pw_time_;
}
void ClientKeepAliveResp::set_pw_time(::google::protobuf::uint64 value) {
  
  pw_time_ = value;
  // @@protoc_insertion_point(field_set:NetProto.C2PW.ClientKeepAliveResp.pw_time)
}

// uint32 multiple = 3;
void ClientKeepAliveResp::clear_multiple() {
  multiple_ = 0u;
}
::google::protobuf::uint32 ClientKeepAliveResp::multiple() const {
  // @@protoc_insertion_point(field_get:NetProto.C2PW.ClientKeepAliveResp.multiple)
  return multiple_;
}
void ClientKeepAliveResp::set_multiple(::google::protobuf::uint32 value) {
  
  multiple_ = value;
  // @@protoc_insertion_point(field_set:NetProto.C2PW.ClientKeepAliveResp.multiple)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace C2PW
}  // namespace NetProto

// @@protoc_insertion_point(global_scope)
