// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gs_2_pw.proto

#ifndef PROTOBUF_gs_5f2_5fpw_2eproto__INCLUDED
#define PROTOBUF_gs_5f2_5fpw_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace NetProto {
namespace gs2pw {
class ServerKeepAliveReq;
class ServerKeepAliveReqDefaultTypeInternal;
extern ServerKeepAliveReqDefaultTypeInternal _ServerKeepAliveReq_default_instance_;
class ServerKeepAliveResp;
class ServerKeepAliveRespDefaultTypeInternal;
extern ServerKeepAliveRespDefaultTypeInternal _ServerKeepAliveResp_default_instance_;
}  // namespace gs2pw
}  // namespace NetProto

namespace NetProto {
namespace gs2pw {

namespace protobuf_gs_5f2_5fpw_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_gs_5f2_5fpw_2eproto

// ===================================================================

class ServerKeepAliveReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NetProto.gs2pw.ServerKeepAliveReq) */ {
 public:
  ServerKeepAliveReq();
  virtual ~ServerKeepAliveReq();

  ServerKeepAliveReq(const ServerKeepAliveReq& from);

  inline ServerKeepAliveReq& operator=(const ServerKeepAliveReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerKeepAliveReq& default_instance();

  static inline const ServerKeepAliveReq* internal_default_instance() {
    return reinterpret_cast<const ServerKeepAliveReq*>(
               &_ServerKeepAliveReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ServerKeepAliveReq* other);

  // implements Message ----------------------------------------------

  inline ServerKeepAliveReq* New() const PROTOBUF_FINAL { return New(NULL); }

  ServerKeepAliveReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ServerKeepAliveReq& from);
  void MergeFrom(const ServerKeepAliveReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ServerKeepAliveReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 gs_id = 1;
  void clear_gs_id();
  static const int kGsIdFieldNumber = 1;
  ::google::protobuf::uint32 gs_id() const;
  void set_gs_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:NetProto.gs2pw.ServerKeepAliveReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 gs_id_;
  mutable int _cached_size_;
  friend struct protobuf_gs_5f2_5fpw_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ServerKeepAliveResp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NetProto.gs2pw.ServerKeepAliveResp) */ {
 public:
  ServerKeepAliveResp();
  virtual ~ServerKeepAliveResp();

  ServerKeepAliveResp(const ServerKeepAliveResp& from);

  inline ServerKeepAliveResp& operator=(const ServerKeepAliveResp& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerKeepAliveResp& default_instance();

  static inline const ServerKeepAliveResp* internal_default_instance() {
    return reinterpret_cast<const ServerKeepAliveResp*>(
               &_ServerKeepAliveResp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(ServerKeepAliveResp* other);

  // implements Message ----------------------------------------------

  inline ServerKeepAliveResp* New() const PROTOBUF_FINAL { return New(NULL); }

  ServerKeepAliveResp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ServerKeepAliveResp& from);
  void MergeFrom(const ServerKeepAliveResp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ServerKeepAliveResp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 pw_time = 2;
  void clear_pw_time();
  static const int kPwTimeFieldNumber = 2;
  ::google::protobuf::uint64 pw_time() const;
  void set_pw_time(::google::protobuf::uint64 value);

  // uint32 pw_id = 1;
  void clear_pw_id();
  static const int kPwIdFieldNumber = 1;
  ::google::protobuf::uint32 pw_id() const;
  void set_pw_id(::google::protobuf::uint32 value);

  // uint32 multiple = 3;
  void clear_multiple();
  static const int kMultipleFieldNumber = 3;
  ::google::protobuf::uint32 multiple() const;
  void set_multiple(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:NetProto.gs2pw.ServerKeepAliveResp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 pw_time_;
  ::google::protobuf::uint32 pw_id_;
  ::google::protobuf::uint32 multiple_;
  mutable int _cached_size_;
  friend struct protobuf_gs_5f2_5fpw_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ServerKeepAliveReq

// uint32 gs_id = 1;
inline void ServerKeepAliveReq::clear_gs_id() {
  gs_id_ = 0u;
}
inline ::google::protobuf::uint32 ServerKeepAliveReq::gs_id() const {
  // @@protoc_insertion_point(field_get:NetProto.gs2pw.ServerKeepAliveReq.gs_id)
  return gs_id_;
}
inline void ServerKeepAliveReq::set_gs_id(::google::protobuf::uint32 value) {
  
  gs_id_ = value;
  // @@protoc_insertion_point(field_set:NetProto.gs2pw.ServerKeepAliveReq.gs_id)
}

// -------------------------------------------------------------------

// ServerKeepAliveResp

// uint32 pw_id = 1;
inline void ServerKeepAliveResp::clear_pw_id() {
  pw_id_ = 0u;
}
inline ::google::protobuf::uint32 ServerKeepAliveResp::pw_id() const {
  // @@protoc_insertion_point(field_get:NetProto.gs2pw.ServerKeepAliveResp.pw_id)
  return pw_id_;
}
inline void ServerKeepAliveResp::set_pw_id(::google::protobuf::uint32 value) {
  
  pw_id_ = value;
  // @@protoc_insertion_point(field_set:NetProto.gs2pw.ServerKeepAliveResp.pw_id)
}

// uint64 pw_time = 2;
inline void ServerKeepAliveResp::clear_pw_time() {
  pw_time_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ServerKeepAliveResp::pw_time() const {
  // @@protoc_insertion_point(field_get:NetProto.gs2pw.ServerKeepAliveResp.pw_time)
  return pw_time_;
}
inline void ServerKeepAliveResp::set_pw_time(::google::protobuf::uint64 value) {
  
  pw_time_ = value;
  // @@protoc_insertion_point(field_set:NetProto.gs2pw.ServerKeepAliveResp.pw_time)
}

// uint32 multiple = 3;
inline void ServerKeepAliveResp::clear_multiple() {
  multiple_ = 0u;
}
inline ::google::protobuf::uint32 ServerKeepAliveResp::multiple() const {
  // @@protoc_insertion_point(field_get:NetProto.gs2pw.ServerKeepAliveResp.multiple)
  return multiple_;
}
inline void ServerKeepAliveResp::set_multiple(::google::protobuf::uint32 value) {
  
  multiple_ = value;
  // @@protoc_insertion_point(field_set:NetProto.gs2pw.ServerKeepAliveResp.multiple)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace gs2pw
}  // namespace NetProto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_gs_5f2_5fpw_2eproto__INCLUDED
