// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my_proto.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "my_proto.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace NetProto {
namespace Action {
namespace Status {
class PretendDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<Pretend> {
} _Pretend_default_instance_;

namespace protobuf_my_5fproto_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pretend, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pretend, container_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Pretend, obj_id_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(Pretend)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_Pretend_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "my_proto.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _Pretend_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _Pretend_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\016my_proto.proto\022\026NetProto.Action.Status"
      "\"/\n\007Pretend\022\024\n\014container_id\030\n \001(\t\022\016\n\006obj"
      "_id\030\024 \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 97);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "my_proto.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_my_5fproto_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Pretend::kContainerIdFieldNumber;
const int Pretend::kObjIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Pretend::Pretend()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_my_5fproto_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:NetProto.Action.Status.Pretend)
}
Pretend::Pretend(const Pretend& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  container_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.container_id().size() > 0) {
    container_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.container_id_);
  }
  obj_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.obj_id().size() > 0) {
    obj_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.obj_id_);
  }
  // @@protoc_insertion_point(copy_constructor:NetProto.Action.Status.Pretend)
}

void Pretend::SharedCtor() {
  container_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  obj_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

Pretend::~Pretend() {
  // @@protoc_insertion_point(destructor:NetProto.Action.Status.Pretend)
  SharedDtor();
}

void Pretend::SharedDtor() {
  container_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  obj_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Pretend::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Pretend::descriptor() {
  protobuf_my_5fproto_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_my_5fproto_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Pretend& Pretend::default_instance() {
  protobuf_my_5fproto_2eproto::InitDefaults();
  return *internal_default_instance();
}

Pretend* Pretend::New(::google::protobuf::Arena* arena) const {
  Pretend* n = new Pretend;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Pretend::Clear() {
// @@protoc_insertion_point(message_clear_start:NetProto.Action.Status.Pretend)
  container_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  obj_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool Pretend::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:NetProto.Action.Status.Pretend)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string container_id = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_container_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->container_id().data(), this->container_id().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "NetProto.Action.Status.Pretend.container_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string obj_id = 20;
      case 20: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(162u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_obj_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->obj_id().data(), this->obj_id().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "NetProto.Action.Status.Pretend.obj_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:NetProto.Action.Status.Pretend)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:NetProto.Action.Status.Pretend)
  return false;
#undef DO_
}

void Pretend::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:NetProto.Action.Status.Pretend)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string container_id = 10;
  if (this->container_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->container_id().data(), this->container_id().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "NetProto.Action.Status.Pretend.container_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      10, this->container_id(), output);
  }

  // string obj_id = 20;
  if (this->obj_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->obj_id().data(), this->obj_id().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "NetProto.Action.Status.Pretend.obj_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      20, this->obj_id(), output);
  }

  // @@protoc_insertion_point(serialize_end:NetProto.Action.Status.Pretend)
}

::google::protobuf::uint8* Pretend::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:NetProto.Action.Status.Pretend)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string container_id = 10;
  if (this->container_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->container_id().data(), this->container_id().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "NetProto.Action.Status.Pretend.container_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->container_id(), target);
  }

  // string obj_id = 20;
  if (this->obj_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->obj_id().data(), this->obj_id().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "NetProto.Action.Status.Pretend.obj_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        20, this->obj_id(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:NetProto.Action.Status.Pretend)
  return target;
}

size_t Pretend::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NetProto.Action.Status.Pretend)
  size_t total_size = 0;

  // string container_id = 10;
  if (this->container_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->container_id());
  }

  // string obj_id = 20;
  if (this->obj_id().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->obj_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Pretend::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:NetProto.Action.Status.Pretend)
  GOOGLE_DCHECK_NE(&from, this);
  const Pretend* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Pretend>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:NetProto.Action.Status.Pretend)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:NetProto.Action.Status.Pretend)
    MergeFrom(*source);
  }
}

void Pretend::MergeFrom(const Pretend& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NetProto.Action.Status.Pretend)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.container_id().size() > 0) {

    container_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.container_id_);
  }
  if (from.obj_id().size() > 0) {

    obj_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.obj_id_);
  }
}

void Pretend::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:NetProto.Action.Status.Pretend)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Pretend::CopyFrom(const Pretend& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NetProto.Action.Status.Pretend)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Pretend::IsInitialized() const {
  return true;
}

void Pretend::Swap(Pretend* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Pretend::InternalSwap(Pretend* other) {
  container_id_.Swap(&other->container_id_);
  obj_id_.Swap(&other->obj_id_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Pretend::GetMetadata() const {
  protobuf_my_5fproto_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_my_5fproto_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Pretend

// string container_id = 10;
void Pretend::clear_container_id() {
  container_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Pretend::container_id() const {
  // @@protoc_insertion_point(field_get:NetProto.Action.Status.Pretend.container_id)
  return container_id_.GetNoArena();
}
void Pretend::set_container_id(const ::std::string& value) {
  
  container_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:NetProto.Action.Status.Pretend.container_id)
}
#if LANG_CXX11
void Pretend::set_container_id(::std::string&& value) {
  
  container_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:NetProto.Action.Status.Pretend.container_id)
}
#endif
void Pretend::set_container_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  container_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:NetProto.Action.Status.Pretend.container_id)
}
void Pretend::set_container_id(const char* value, size_t size) {
  
  container_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:NetProto.Action.Status.Pretend.container_id)
}
::std::string* Pretend::mutable_container_id() {
  
  // @@protoc_insertion_point(field_mutable:NetProto.Action.Status.Pretend.container_id)
  return container_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Pretend::release_container_id() {
  // @@protoc_insertion_point(field_release:NetProto.Action.Status.Pretend.container_id)
  
  return container_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Pretend::set_allocated_container_id(::std::string* container_id) {
  if (container_id != NULL) {
    
  } else {
    
  }
  container_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), container_id);
  // @@protoc_insertion_point(field_set_allocated:NetProto.Action.Status.Pretend.container_id)
}

// string obj_id = 20;
void Pretend::clear_obj_id() {
  obj_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Pretend::obj_id() const {
  // @@protoc_insertion_point(field_get:NetProto.Action.Status.Pretend.obj_id)
  return obj_id_.GetNoArena();
}
void Pretend::set_obj_id(const ::std::string& value) {
  
  obj_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:NetProto.Action.Status.Pretend.obj_id)
}
#if LANG_CXX11
void Pretend::set_obj_id(::std::string&& value) {
  
  obj_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:NetProto.Action.Status.Pretend.obj_id)
}
#endif
void Pretend::set_obj_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  obj_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:NetProto.Action.Status.Pretend.obj_id)
}
void Pretend::set_obj_id(const char* value, size_t size) {
  
  obj_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:NetProto.Action.Status.Pretend.obj_id)
}
::std::string* Pretend::mutable_obj_id() {
  
  // @@protoc_insertion_point(field_mutable:NetProto.Action.Status.Pretend.obj_id)
  return obj_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Pretend::release_obj_id() {
  // @@protoc_insertion_point(field_release:NetProto.Action.Status.Pretend.obj_id)
  
  return obj_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Pretend::set_allocated_obj_id(::std::string* obj_id) {
  if (obj_id != NULL) {
    
  } else {
    
  }
  obj_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), obj_id);
  // @@protoc_insertion_point(field_set_allocated:NetProto.Action.Status.Pretend.obj_id)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Status
}  // namespace Action
}  // namespace NetProto

// @@protoc_insertion_point(global_scope)
