// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pos_rot.proto

#ifndef PROTOBUF_pos_5frot_2eproto__INCLUDED
#define PROTOBUF_pos_5frot_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "quaternion.pb.h"
#include "vector3.pb.h"
// @@protoc_insertion_point(includes)
namespace NetProto {
class PosRot;
class PosRotDefaultTypeInternal;
extern PosRotDefaultTypeInternal _PosRot_default_instance_;
class Quaternion;
class QuaternionDefaultTypeInternal;
extern QuaternionDefaultTypeInternal _Quaternion_default_instance_;
class Vector3;
class Vector3DefaultTypeInternal;
extern Vector3DefaultTypeInternal _Vector3_default_instance_;
}  // namespace NetProto

namespace NetProto {

namespace protobuf_pos_5frot_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_pos_5frot_2eproto

// ===================================================================

class PosRot : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NetProto.PosRot) */ {
 public:
  PosRot();
  virtual ~PosRot();

  PosRot(const PosRot& from);

  inline PosRot& operator=(const PosRot& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PosRot& default_instance();

  static inline const PosRot* internal_default_instance() {
    return reinterpret_cast<const PosRot*>(
               &_PosRot_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(PosRot* other);

  // implements Message ----------------------------------------------

  inline PosRot* New() const PROTOBUF_FINAL { return New(NULL); }

  PosRot* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PosRot& from);
  void MergeFrom(const PosRot& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PosRot* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .NetProto.Quaternion rotation = 1;
  bool has_rotation() const;
  void clear_rotation();
  static const int kRotationFieldNumber = 1;
  const ::NetProto::Quaternion& rotation() const;
  ::NetProto::Quaternion* mutable_rotation();
  ::NetProto::Quaternion* release_rotation();
  void set_allocated_rotation(::NetProto::Quaternion* rotation);

  // .NetProto.Vector3 position = 2;
  bool has_position() const;
  void clear_position();
  static const int kPositionFieldNumber = 2;
  const ::NetProto::Vector3& position() const;
  ::NetProto::Vector3* mutable_position();
  ::NetProto::Vector3* release_position();
  void set_allocated_position(::NetProto::Vector3* position);

  // @@protoc_insertion_point(class_scope:NetProto.PosRot)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::NetProto::Quaternion* rotation_;
  ::NetProto::Vector3* position_;
  mutable int _cached_size_;
  friend struct protobuf_pos_5frot_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// PosRot

// .NetProto.Quaternion rotation = 1;
inline bool PosRot::has_rotation() const {
  return this != internal_default_instance() && rotation_ != NULL;
}
inline void PosRot::clear_rotation() {
  if (GetArenaNoVirtual() == NULL && rotation_ != NULL) delete rotation_;
  rotation_ = NULL;
}
inline const ::NetProto::Quaternion& PosRot::rotation() const {
  // @@protoc_insertion_point(field_get:NetProto.PosRot.rotation)
  return rotation_ != NULL ? *rotation_
                         : *::NetProto::Quaternion::internal_default_instance();
}
inline ::NetProto::Quaternion* PosRot::mutable_rotation() {
  
  if (rotation_ == NULL) {
    rotation_ = new ::NetProto::Quaternion;
  }
  // @@protoc_insertion_point(field_mutable:NetProto.PosRot.rotation)
  return rotation_;
}
inline ::NetProto::Quaternion* PosRot::release_rotation() {
  // @@protoc_insertion_point(field_release:NetProto.PosRot.rotation)
  
  ::NetProto::Quaternion* temp = rotation_;
  rotation_ = NULL;
  return temp;
}
inline void PosRot::set_allocated_rotation(::NetProto::Quaternion* rotation) {
  delete rotation_;
  rotation_ = rotation;
  if (rotation) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:NetProto.PosRot.rotation)
}

// .NetProto.Vector3 position = 2;
inline bool PosRot::has_position() const {
  return this != internal_default_instance() && position_ != NULL;
}
inline void PosRot::clear_position() {
  if (GetArenaNoVirtual() == NULL && position_ != NULL) delete position_;
  position_ = NULL;
}
inline const ::NetProto::Vector3& PosRot::position() const {
  // @@protoc_insertion_point(field_get:NetProto.PosRot.position)
  return position_ != NULL ? *position_
                         : *::NetProto::Vector3::internal_default_instance();
}
inline ::NetProto::Vector3* PosRot::mutable_position() {
  
  if (position_ == NULL) {
    position_ = new ::NetProto::Vector3;
  }
  // @@protoc_insertion_point(field_mutable:NetProto.PosRot.position)
  return position_;
}
inline ::NetProto::Vector3* PosRot::release_position() {
  // @@protoc_insertion_point(field_release:NetProto.PosRot.position)
  
  ::NetProto::Vector3* temp = position_;
  position_ = NULL;
  return temp;
}
inline void PosRot::set_allocated_position(::NetProto::Vector3* position) {
  delete position_;
  position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:NetProto.PosRot.position)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace NetProto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pos_5frot_2eproto__INCLUDED
