// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather_raw_data.proto

#ifndef PROTOBUF_weather_5fraw_5fdata_2eproto__INCLUDED
#define PROTOBUF_weather_5fraw_5fdata_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "msg_head.pb.h"
// @@protoc_insertion_point(includes)
namespace NetProto {
class MsgHead;
class MsgHeadDefaultTypeInternal;
extern MsgHeadDefaultTypeInternal _MsgHead_default_instance_;
class WeatherRawData;
class WeatherRawDataDefaultTypeInternal;
extern WeatherRawDataDefaultTypeInternal _WeatherRawData_default_instance_;
}  // namespace NetProto

namespace NetProto {

namespace protobuf_weather_5fraw_5fdata_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_weather_5fraw_5fdata_2eproto

// ===================================================================

class WeatherRawData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NetProto.WeatherRawData) */ {
 public:
  WeatherRawData();
  virtual ~WeatherRawData();

  WeatherRawData(const WeatherRawData& from);

  inline WeatherRawData& operator=(const WeatherRawData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WeatherRawData& default_instance();

  static inline const WeatherRawData* internal_default_instance() {
    return reinterpret_cast<const WeatherRawData*>(
               &_WeatherRawData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(WeatherRawData* other);

  // implements Message ----------------------------------------------

  inline WeatherRawData* New() const PROTOBUF_FINAL { return New(NULL); }

  WeatherRawData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const WeatherRawData& from);
  void MergeFrom(const WeatherRawData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(WeatherRawData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .NetProto.MsgHead head = 1;
  bool has_head() const;
  void clear_head();
  static const int kHeadFieldNumber = 1;
  const ::NetProto::MsgHead& head() const;
  ::NetProto::MsgHead* mutable_head();
  ::NetProto::MsgHead* release_head();
  void set_allocated_head(::NetProto::MsgHead* head);

  // float sunshine_level = 2;
  void clear_sunshine_level();
  static const int kSunshineLevelFieldNumber = 2;
  float sunshine_level() const;
  void set_sunshine_level(float value);

  // float sun_angle_elevation = 3;
  void clear_sun_angle_elevation();
  static const int kSunAngleElevationFieldNumber = 3;
  float sun_angle_elevation() const;
  void set_sun_angle_elevation(float value);

  // float sun_angle_azimuth = 4;
  void clear_sun_angle_azimuth();
  static const int kSunAngleAzimuthFieldNumber = 4;
  float sun_angle_azimuth() const;
  void set_sun_angle_azimuth(float value);

  // float cloud_level = 5;
  void clear_cloud_level();
  static const int kCloudLevelFieldNumber = 5;
  float cloud_level() const;
  void set_cloud_level(float value);

  // float temperature_level = 6;
  void clear_temperature_level();
  static const int kTemperatureLevelFieldNumber = 6;
  float temperature_level() const;
  void set_temperature_level(float value);

  // float rain_flag = 7;
  void clear_rain_flag();
  static const int kRainFlagFieldNumber = 7;
  float rain_flag() const;
  void set_rain_flag(float value);

  // float rain_level = 8;
  void clear_rain_level();
  static const int kRainLevelFieldNumber = 8;
  float rain_level() const;
  void set_rain_level(float value);

  // float snow_level = 9;
  void clear_snow_level();
  static const int kSnowLevelFieldNumber = 9;
  float snow_level() const;
  void set_snow_level(float value);

  // float hail_level = 10;
  void clear_hail_level();
  static const int kHailLevelFieldNumber = 10;
  float hail_level() const;
  void set_hail_level(float value);

  // float thunder_level = 11;
  void clear_thunder_level();
  static const int kThunderLevelFieldNumber = 11;
  float thunder_level() const;
  void set_thunder_level(float value);

  // float moon_wanes = 12;
  void clear_moon_wanes();
  static const int kMoonWanesFieldNumber = 12;
  float moon_wanes() const;
  void set_moon_wanes(float value);

  // float moon_shape = 13;
  void clear_moon_shape();
  static const int kMoonShapeFieldNumber = 13;
  float moon_shape() const;
  void set_moon_shape(float value);

  // float sun_rise = 14;
  void clear_sun_rise();
  static const int kSunRiseFieldNumber = 14;
  float sun_rise() const;
  void set_sun_rise(float value);

  // float sun_fall = 15;
  void clear_sun_fall();
  static const int kSunFallFieldNumber = 15;
  float sun_fall() const;
  void set_sun_fall(float value);

  // float wind_level = 16;
  void clear_wind_level();
  static const int kWindLevelFieldNumber = 16;
  float wind_level() const;
  void set_wind_level(float value);

  // float typhoon_flag = 17;
  void clear_typhoon_flag();
  static const int kTyphoonFlagFieldNumber = 17;
  float typhoon_flag() const;
  void set_typhoon_flag(float value);

  // float typhoon_level = 18;
  void clear_typhoon_level();
  static const int kTyphoonLevelFieldNumber = 18;
  float typhoon_level() const;
  void set_typhoon_level(float value);

  // float meteor_flag = 19;
  void clear_meteor_flag();
  static const int kMeteorFlagFieldNumber = 19;
  float meteor_flag() const;
  void set_meteor_flag(float value);

  // float meteor_level = 20;
  void clear_meteor_level();
  static const int kMeteorLevelFieldNumber = 20;
  float meteor_level() const;
  void set_meteor_level(float value);

  // float ice_level = 21;
  void clear_ice_level();
  static const int kIceLevelFieldNumber = 21;
  float ice_level() const;
  void set_ice_level(float value);

  // float warmwinter_flag = 22;
  void clear_warmwinter_flag();
  static const int kWarmwinterFlagFieldNumber = 22;
  float warmwinter_flag() const;
  void set_warmwinter_flag(float value);

  // float humidity_level = 23;
  void clear_humidity_level();
  static const int kHumidityLevelFieldNumber = 23;
  float humidity_level() const;
  void set_humidity_level(float value);

  // @@protoc_insertion_point(class_scope:NetProto.WeatherRawData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::NetProto::MsgHead* head_;
  float sunshine_level_;
  float sun_angle_elevation_;
  float sun_angle_azimuth_;
  float cloud_level_;
  float temperature_level_;
  float rain_flag_;
  float rain_level_;
  float snow_level_;
  float hail_level_;
  float thunder_level_;
  float moon_wanes_;
  float moon_shape_;
  float sun_rise_;
  float sun_fall_;
  float wind_level_;
  float typhoon_flag_;
  float typhoon_level_;
  float meteor_flag_;
  float meteor_level_;
  float ice_level_;
  float warmwinter_flag_;
  float humidity_level_;
  mutable int _cached_size_;
  friend struct protobuf_weather_5fraw_5fdata_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// WeatherRawData

// .NetProto.MsgHead head = 1;
inline bool WeatherRawData::has_head() const {
  return this != internal_default_instance() && head_ != NULL;
}
inline void WeatherRawData::clear_head() {
  if (GetArenaNoVirtual() == NULL && head_ != NULL) delete head_;
  head_ = NULL;
}
inline const ::NetProto::MsgHead& WeatherRawData::head() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.head)
  return head_ != NULL ? *head_
                         : *::NetProto::MsgHead::internal_default_instance();
}
inline ::NetProto::MsgHead* WeatherRawData::mutable_head() {
  
  if (head_ == NULL) {
    head_ = new ::NetProto::MsgHead;
  }
  // @@protoc_insertion_point(field_mutable:NetProto.WeatherRawData.head)
  return head_;
}
inline ::NetProto::MsgHead* WeatherRawData::release_head() {
  // @@protoc_insertion_point(field_release:NetProto.WeatherRawData.head)
  
  ::NetProto::MsgHead* temp = head_;
  head_ = NULL;
  return temp;
}
inline void WeatherRawData::set_allocated_head(::NetProto::MsgHead* head) {
  delete head_;
  head_ = head;
  if (head) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:NetProto.WeatherRawData.head)
}

// float sunshine_level = 2;
inline void WeatherRawData::clear_sunshine_level() {
  sunshine_level_ = 0;
}
inline float WeatherRawData::sunshine_level() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.sunshine_level)
  return sunshine_level_;
}
inline void WeatherRawData::set_sunshine_level(float value) {
  
  sunshine_level_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.sunshine_level)
}

// float sun_angle_elevation = 3;
inline void WeatherRawData::clear_sun_angle_elevation() {
  sun_angle_elevation_ = 0;
}
inline float WeatherRawData::sun_angle_elevation() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.sun_angle_elevation)
  return sun_angle_elevation_;
}
inline void WeatherRawData::set_sun_angle_elevation(float value) {
  
  sun_angle_elevation_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.sun_angle_elevation)
}

// float sun_angle_azimuth = 4;
inline void WeatherRawData::clear_sun_angle_azimuth() {
  sun_angle_azimuth_ = 0;
}
inline float WeatherRawData::sun_angle_azimuth() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.sun_angle_azimuth)
  return sun_angle_azimuth_;
}
inline void WeatherRawData::set_sun_angle_azimuth(float value) {
  
  sun_angle_azimuth_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.sun_angle_azimuth)
}

// float cloud_level = 5;
inline void WeatherRawData::clear_cloud_level() {
  cloud_level_ = 0;
}
inline float WeatherRawData::cloud_level() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.cloud_level)
  return cloud_level_;
}
inline void WeatherRawData::set_cloud_level(float value) {
  
  cloud_level_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.cloud_level)
}

// float temperature_level = 6;
inline void WeatherRawData::clear_temperature_level() {
  temperature_level_ = 0;
}
inline float WeatherRawData::temperature_level() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.temperature_level)
  return temperature_level_;
}
inline void WeatherRawData::set_temperature_level(float value) {
  
  temperature_level_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.temperature_level)
}

// float rain_flag = 7;
inline void WeatherRawData::clear_rain_flag() {
  rain_flag_ = 0;
}
inline float WeatherRawData::rain_flag() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.rain_flag)
  return rain_flag_;
}
inline void WeatherRawData::set_rain_flag(float value) {
  
  rain_flag_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.rain_flag)
}

// float rain_level = 8;
inline void WeatherRawData::clear_rain_level() {
  rain_level_ = 0;
}
inline float WeatherRawData::rain_level() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.rain_level)
  return rain_level_;
}
inline void WeatherRawData::set_rain_level(float value) {
  
  rain_level_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.rain_level)
}

// float snow_level = 9;
inline void WeatherRawData::clear_snow_level() {
  snow_level_ = 0;
}
inline float WeatherRawData::snow_level() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.snow_level)
  return snow_level_;
}
inline void WeatherRawData::set_snow_level(float value) {
  
  snow_level_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.snow_level)
}

// float hail_level = 10;
inline void WeatherRawData::clear_hail_level() {
  hail_level_ = 0;
}
inline float WeatherRawData::hail_level() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.hail_level)
  return hail_level_;
}
inline void WeatherRawData::set_hail_level(float value) {
  
  hail_level_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.hail_level)
}

// float thunder_level = 11;
inline void WeatherRawData::clear_thunder_level() {
  thunder_level_ = 0;
}
inline float WeatherRawData::thunder_level() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.thunder_level)
  return thunder_level_;
}
inline void WeatherRawData::set_thunder_level(float value) {
  
  thunder_level_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.thunder_level)
}

// float moon_wanes = 12;
inline void WeatherRawData::clear_moon_wanes() {
  moon_wanes_ = 0;
}
inline float WeatherRawData::moon_wanes() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.moon_wanes)
  return moon_wanes_;
}
inline void WeatherRawData::set_moon_wanes(float value) {
  
  moon_wanes_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.moon_wanes)
}

// float moon_shape = 13;
inline void WeatherRawData::clear_moon_shape() {
  moon_shape_ = 0;
}
inline float WeatherRawData::moon_shape() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.moon_shape)
  return moon_shape_;
}
inline void WeatherRawData::set_moon_shape(float value) {
  
  moon_shape_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.moon_shape)
}

// float sun_rise = 14;
inline void WeatherRawData::clear_sun_rise() {
  sun_rise_ = 0;
}
inline float WeatherRawData::sun_rise() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.sun_rise)
  return sun_rise_;
}
inline void WeatherRawData::set_sun_rise(float value) {
  
  sun_rise_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.sun_rise)
}

// float sun_fall = 15;
inline void WeatherRawData::clear_sun_fall() {
  sun_fall_ = 0;
}
inline float WeatherRawData::sun_fall() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.sun_fall)
  return sun_fall_;
}
inline void WeatherRawData::set_sun_fall(float value) {
  
  sun_fall_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.sun_fall)
}

// float wind_level = 16;
inline void WeatherRawData::clear_wind_level() {
  wind_level_ = 0;
}
inline float WeatherRawData::wind_level() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.wind_level)
  return wind_level_;
}
inline void WeatherRawData::set_wind_level(float value) {
  
  wind_level_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.wind_level)
}

// float typhoon_flag = 17;
inline void WeatherRawData::clear_typhoon_flag() {
  typhoon_flag_ = 0;
}
inline float WeatherRawData::typhoon_flag() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.typhoon_flag)
  return typhoon_flag_;
}
inline void WeatherRawData::set_typhoon_flag(float value) {
  
  typhoon_flag_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.typhoon_flag)
}

// float typhoon_level = 18;
inline void WeatherRawData::clear_typhoon_level() {
  typhoon_level_ = 0;
}
inline float WeatherRawData::typhoon_level() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.typhoon_level)
  return typhoon_level_;
}
inline void WeatherRawData::set_typhoon_level(float value) {
  
  typhoon_level_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.typhoon_level)
}

// float meteor_flag = 19;
inline void WeatherRawData::clear_meteor_flag() {
  meteor_flag_ = 0;
}
inline float WeatherRawData::meteor_flag() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.meteor_flag)
  return meteor_flag_;
}
inline void WeatherRawData::set_meteor_flag(float value) {
  
  meteor_flag_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.meteor_flag)
}

// float meteor_level = 20;
inline void WeatherRawData::clear_meteor_level() {
  meteor_level_ = 0;
}
inline float WeatherRawData::meteor_level() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.meteor_level)
  return meteor_level_;
}
inline void WeatherRawData::set_meteor_level(float value) {
  
  meteor_level_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.meteor_level)
}

// float ice_level = 21;
inline void WeatherRawData::clear_ice_level() {
  ice_level_ = 0;
}
inline float WeatherRawData::ice_level() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.ice_level)
  return ice_level_;
}
inline void WeatherRawData::set_ice_level(float value) {
  
  ice_level_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.ice_level)
}

// float warmwinter_flag = 22;
inline void WeatherRawData::clear_warmwinter_flag() {
  warmwinter_flag_ = 0;
}
inline float WeatherRawData::warmwinter_flag() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.warmwinter_flag)
  return warmwinter_flag_;
}
inline void WeatherRawData::set_warmwinter_flag(float value) {
  
  warmwinter_flag_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.warmwinter_flag)
}

// float humidity_level = 23;
inline void WeatherRawData::clear_humidity_level() {
  humidity_level_ = 0;
}
inline float WeatherRawData::humidity_level() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherRawData.humidity_level)
  return humidity_level_;
}
inline void WeatherRawData::set_humidity_level(float value) {
  
  humidity_level_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherRawData.humidity_level)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace NetProto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_weather_5fraw_5fdata_2eproto__INCLUDED
