// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather_item_2_client.proto

#ifndef PROTOBUF_weather_5fitem_5f2_5fclient_2eproto__INCLUDED
#define PROTOBUF_weather_5fitem_5f2_5fclient_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "msg_head.pb.h"
// @@protoc_insertion_point(includes)
namespace NetProto {
class MsgHead;
class MsgHeadDefaultTypeInternal;
extern MsgHeadDefaultTypeInternal _MsgHead_default_instance_;
class WeatherItem;
class WeatherItemDefaultTypeInternal;
extern WeatherItemDefaultTypeInternal _WeatherItem_default_instance_;
}  // namespace NetProto

namespace NetProto {

namespace protobuf_weather_5fitem_5f2_5fclient_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_weather_5fitem_5f2_5fclient_2eproto

// ===================================================================

class WeatherItem : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NetProto.WeatherItem) */ {
 public:
  WeatherItem();
  virtual ~WeatherItem();

  WeatherItem(const WeatherItem& from);

  inline WeatherItem& operator=(const WeatherItem& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const WeatherItem& default_instance();

  static inline const WeatherItem* internal_default_instance() {
    return reinterpret_cast<const WeatherItem*>(
               &_WeatherItem_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(WeatherItem* other);

  // implements Message ----------------------------------------------

  inline WeatherItem* New() const PROTOBUF_FINAL { return New(NULL); }

  WeatherItem* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const WeatherItem& from);
  void MergeFrom(const WeatherItem& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(WeatherItem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .NetProto.MsgHead head = 1;
  bool has_head() const;
  void clear_head();
  static const int kHeadFieldNumber = 1;
  const ::NetProto::MsgHead& head() const;
  ::NetProto::MsgHead* mutable_head();
  ::NetProto::MsgHead* release_head();
  void set_allocated_head(::NetProto::MsgHead* head);

  // uint32 sun_shine = 2;
  void clear_sun_shine();
  static const int kSunShineFieldNumber = 2;
  ::google::protobuf::uint32 sun_shine() const;
  void set_sun_shine(::google::protobuf::uint32 value);

  // uint32 cloud = 3;
  void clear_cloud();
  static const int kCloudFieldNumber = 3;
  ::google::protobuf::uint32 cloud() const;
  void set_cloud(::google::protobuf::uint32 value);

  // uint32 rain = 4;
  void clear_rain();
  static const int kRainFieldNumber = 4;
  ::google::protobuf::uint32 rain() const;
  void set_rain(::google::protobuf::uint32 value);

  // uint32 hail = 5;
  void clear_hail();
  static const int kHailFieldNumber = 5;
  ::google::protobuf::uint32 hail() const;
  void set_hail(::google::protobuf::uint32 value);

  // uint32 moon = 6;
  void clear_moon();
  static const int kMoonFieldNumber = 6;
  ::google::protobuf::uint32 moon() const;
  void set_moon(::google::protobuf::uint32 value);

  // uint32 thunder = 7;
  void clear_thunder();
  static const int kThunderFieldNumber = 7;
  ::google::protobuf::uint32 thunder() const;
  void set_thunder(::google::protobuf::uint32 value);

  // uint32 snow = 8;
  void clear_snow();
  static const int kSnowFieldNumber = 8;
  ::google::protobuf::uint32 snow() const;
  void set_snow(::google::protobuf::uint32 value);

  // uint32 wind = 12;
  void clear_wind();
  static const int kWindFieldNumber = 12;
  ::google::protobuf::uint32 wind() const;
  void set_wind(::google::protobuf::uint32 value);

  // uint32 typhoon = 13;
  void clear_typhoon();
  static const int kTyphoonFieldNumber = 13;
  ::google::protobuf::uint32 typhoon() const;
  void set_typhoon(::google::protobuf::uint32 value);

  // uint32 meteor = 14;
  void clear_meteor();
  static const int kMeteorFieldNumber = 14;
  ::google::protobuf::uint32 meteor() const;
  void set_meteor(::google::protobuf::uint32 value);

  // uint32 ice = 15;
  void clear_ice();
  static const int kIceFieldNumber = 15;
  ::google::protobuf::uint32 ice() const;
  void set_ice(::google::protobuf::uint32 value);

  // uint32 vegetation_leaf_a = 18;
  void clear_vegetation_leaf_a();
  static const int kVegetationLeafAFieldNumber = 18;
  ::google::protobuf::uint32 vegetation_leaf_a() const;
  void set_vegetation_leaf_a(::google::protobuf::uint32 value);

  // uint32 vegetation_leaf_b = 19;
  void clear_vegetation_leaf_b();
  static const int kVegetationLeafBFieldNumber = 19;
  ::google::protobuf::uint32 vegetation_leaf_b() const;
  void set_vegetation_leaf_b(::google::protobuf::uint32 value);

  // uint32 vegetation_flower_a = 20;
  void clear_vegetation_flower_a();
  static const int kVegetationFlowerAFieldNumber = 20;
  ::google::protobuf::uint32 vegetation_flower_a() const;
  void set_vegetation_flower_a(::google::protobuf::uint32 value);

  // uint32 vegetation_flower_b = 21;
  void clear_vegetation_flower_b();
  static const int kVegetationFlowerBFieldNumber = 21;
  ::google::protobuf::uint32 vegetation_flower_b() const;
  void set_vegetation_flower_b(::google::protobuf::uint32 value);

  // uint32 temperature = 22;
  void clear_temperature();
  static const int kTemperatureFieldNumber = 22;
  ::google::protobuf::uint32 temperature() const;
  void set_temperature(::google::protobuf::uint32 value);

  // uint32 warmwinter = 24;
  void clear_warmwinter();
  static const int kWarmwinterFieldNumber = 24;
  ::google::protobuf::uint32 warmwinter() const;
  void set_warmwinter(::google::protobuf::uint32 value);

  // uint32 humidity = 25;
  void clear_humidity();
  static const int kHumidityFieldNumber = 25;
  ::google::protobuf::uint32 humidity() const;
  void set_humidity(::google::protobuf::uint32 value);

  // uint32 sun_high_angle = 30;
  void clear_sun_high_angle();
  static const int kSunHighAngleFieldNumber = 30;
  ::google::protobuf::uint32 sun_high_angle() const;
  void set_sun_high_angle(::google::protobuf::uint32 value);

  // uint32 sun_orig_angle = 31;
  void clear_sun_orig_angle();
  static const int kSunOrigAngleFieldNumber = 31;
  ::google::protobuf::uint32 sun_orig_angle() const;
  void set_sun_orig_angle(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:NetProto.WeatherItem)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::NetProto::MsgHead* head_;
  ::google::protobuf::uint32 sun_shine_;
  ::google::protobuf::uint32 cloud_;
  ::google::protobuf::uint32 rain_;
  ::google::protobuf::uint32 hail_;
  ::google::protobuf::uint32 moon_;
  ::google::protobuf::uint32 thunder_;
  ::google::protobuf::uint32 snow_;
  ::google::protobuf::uint32 wind_;
  ::google::protobuf::uint32 typhoon_;
  ::google::protobuf::uint32 meteor_;
  ::google::protobuf::uint32 ice_;
  ::google::protobuf::uint32 vegetation_leaf_a_;
  ::google::protobuf::uint32 vegetation_leaf_b_;
  ::google::protobuf::uint32 vegetation_flower_a_;
  ::google::protobuf::uint32 vegetation_flower_b_;
  ::google::protobuf::uint32 temperature_;
  ::google::protobuf::uint32 warmwinter_;
  ::google::protobuf::uint32 humidity_;
  ::google::protobuf::uint32 sun_high_angle_;
  ::google::protobuf::uint32 sun_orig_angle_;
  mutable int _cached_size_;
  friend struct protobuf_weather_5fitem_5f2_5fclient_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// WeatherItem

// .NetProto.MsgHead head = 1;
inline bool WeatherItem::has_head() const {
  return this != internal_default_instance() && head_ != NULL;
}
inline void WeatherItem::clear_head() {
  if (GetArenaNoVirtual() == NULL && head_ != NULL) delete head_;
  head_ = NULL;
}
inline const ::NetProto::MsgHead& WeatherItem::head() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherItem.head)
  return head_ != NULL ? *head_
                         : *::NetProto::MsgHead::internal_default_instance();
}
inline ::NetProto::MsgHead* WeatherItem::mutable_head() {
  
  if (head_ == NULL) {
    head_ = new ::NetProto::MsgHead;
  }
  // @@protoc_insertion_point(field_mutable:NetProto.WeatherItem.head)
  return head_;
}
inline ::NetProto::MsgHead* WeatherItem::release_head() {
  // @@protoc_insertion_point(field_release:NetProto.WeatherItem.head)
  
  ::NetProto::MsgHead* temp = head_;
  head_ = NULL;
  return temp;
}
inline void WeatherItem::set_allocated_head(::NetProto::MsgHead* head) {
  delete head_;
  head_ = head;
  if (head) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:NetProto.WeatherItem.head)
}

// uint32 sun_shine = 2;
inline void WeatherItem::clear_sun_shine() {
  sun_shine_ = 0u;
}
inline ::google::protobuf::uint32 WeatherItem::sun_shine() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherItem.sun_shine)
  return sun_shine_;
}
inline void WeatherItem::set_sun_shine(::google::protobuf::uint32 value) {
  
  sun_shine_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherItem.sun_shine)
}

// uint32 cloud = 3;
inline void WeatherItem::clear_cloud() {
  cloud_ = 0u;
}
inline ::google::protobuf::uint32 WeatherItem::cloud() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherItem.cloud)
  return cloud_;
}
inline void WeatherItem::set_cloud(::google::protobuf::uint32 value) {
  
  cloud_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherItem.cloud)
}

// uint32 rain = 4;
inline void WeatherItem::clear_rain() {
  rain_ = 0u;
}
inline ::google::protobuf::uint32 WeatherItem::rain() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherItem.rain)
  return rain_;
}
inline void WeatherItem::set_rain(::google::protobuf::uint32 value) {
  
  rain_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherItem.rain)
}

// uint32 hail = 5;
inline void WeatherItem::clear_hail() {
  hail_ = 0u;
}
inline ::google::protobuf::uint32 WeatherItem::hail() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherItem.hail)
  return hail_;
}
inline void WeatherItem::set_hail(::google::protobuf::uint32 value) {
  
  hail_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherItem.hail)
}

// uint32 moon = 6;
inline void WeatherItem::clear_moon() {
  moon_ = 0u;
}
inline ::google::protobuf::uint32 WeatherItem::moon() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherItem.moon)
  return moon_;
}
inline void WeatherItem::set_moon(::google::protobuf::uint32 value) {
  
  moon_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherItem.moon)
}

// uint32 thunder = 7;
inline void WeatherItem::clear_thunder() {
  thunder_ = 0u;
}
inline ::google::protobuf::uint32 WeatherItem::thunder() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherItem.thunder)
  return thunder_;
}
inline void WeatherItem::set_thunder(::google::protobuf::uint32 value) {
  
  thunder_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherItem.thunder)
}

// uint32 snow = 8;
inline void WeatherItem::clear_snow() {
  snow_ = 0u;
}
inline ::google::protobuf::uint32 WeatherItem::snow() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherItem.snow)
  return snow_;
}
inline void WeatherItem::set_snow(::google::protobuf::uint32 value) {
  
  snow_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherItem.snow)
}

// uint32 wind = 12;
inline void WeatherItem::clear_wind() {
  wind_ = 0u;
}
inline ::google::protobuf::uint32 WeatherItem::wind() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherItem.wind)
  return wind_;
}
inline void WeatherItem::set_wind(::google::protobuf::uint32 value) {
  
  wind_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherItem.wind)
}

// uint32 typhoon = 13;
inline void WeatherItem::clear_typhoon() {
  typhoon_ = 0u;
}
inline ::google::protobuf::uint32 WeatherItem::typhoon() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherItem.typhoon)
  return typhoon_;
}
inline void WeatherItem::set_typhoon(::google::protobuf::uint32 value) {
  
  typhoon_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherItem.typhoon)
}

// uint32 meteor = 14;
inline void WeatherItem::clear_meteor() {
  meteor_ = 0u;
}
inline ::google::protobuf::uint32 WeatherItem::meteor() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherItem.meteor)
  return meteor_;
}
inline void WeatherItem::set_meteor(::google::protobuf::uint32 value) {
  
  meteor_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherItem.meteor)
}

// uint32 ice = 15;
inline void WeatherItem::clear_ice() {
  ice_ = 0u;
}
inline ::google::protobuf::uint32 WeatherItem::ice() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherItem.ice)
  return ice_;
}
inline void WeatherItem::set_ice(::google::protobuf::uint32 value) {
  
  ice_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherItem.ice)
}

// uint32 vegetation_leaf_a = 18;
inline void WeatherItem::clear_vegetation_leaf_a() {
  vegetation_leaf_a_ = 0u;
}
inline ::google::protobuf::uint32 WeatherItem::vegetation_leaf_a() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherItem.vegetation_leaf_a)
  return vegetation_leaf_a_;
}
inline void WeatherItem::set_vegetation_leaf_a(::google::protobuf::uint32 value) {
  
  vegetation_leaf_a_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherItem.vegetation_leaf_a)
}

// uint32 vegetation_leaf_b = 19;
inline void WeatherItem::clear_vegetation_leaf_b() {
  vegetation_leaf_b_ = 0u;
}
inline ::google::protobuf::uint32 WeatherItem::vegetation_leaf_b() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherItem.vegetation_leaf_b)
  return vegetation_leaf_b_;
}
inline void WeatherItem::set_vegetation_leaf_b(::google::protobuf::uint32 value) {
  
  vegetation_leaf_b_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherItem.vegetation_leaf_b)
}

// uint32 vegetation_flower_a = 20;
inline void WeatherItem::clear_vegetation_flower_a() {
  vegetation_flower_a_ = 0u;
}
inline ::google::protobuf::uint32 WeatherItem::vegetation_flower_a() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherItem.vegetation_flower_a)
  return vegetation_flower_a_;
}
inline void WeatherItem::set_vegetation_flower_a(::google::protobuf::uint32 value) {
  
  vegetation_flower_a_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherItem.vegetation_flower_a)
}

// uint32 vegetation_flower_b = 21;
inline void WeatherItem::clear_vegetation_flower_b() {
  vegetation_flower_b_ = 0u;
}
inline ::google::protobuf::uint32 WeatherItem::vegetation_flower_b() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherItem.vegetation_flower_b)
  return vegetation_flower_b_;
}
inline void WeatherItem::set_vegetation_flower_b(::google::protobuf::uint32 value) {
  
  vegetation_flower_b_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherItem.vegetation_flower_b)
}

// uint32 temperature = 22;
inline void WeatherItem::clear_temperature() {
  temperature_ = 0u;
}
inline ::google::protobuf::uint32 WeatherItem::temperature() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherItem.temperature)
  return temperature_;
}
inline void WeatherItem::set_temperature(::google::protobuf::uint32 value) {
  
  temperature_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherItem.temperature)
}

// uint32 warmwinter = 24;
inline void WeatherItem::clear_warmwinter() {
  warmwinter_ = 0u;
}
inline ::google::protobuf::uint32 WeatherItem::warmwinter() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherItem.warmwinter)
  return warmwinter_;
}
inline void WeatherItem::set_warmwinter(::google::protobuf::uint32 value) {
  
  warmwinter_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherItem.warmwinter)
}

// uint32 humidity = 25;
inline void WeatherItem::clear_humidity() {
  humidity_ = 0u;
}
inline ::google::protobuf::uint32 WeatherItem::humidity() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherItem.humidity)
  return humidity_;
}
inline void WeatherItem::set_humidity(::google::protobuf::uint32 value) {
  
  humidity_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherItem.humidity)
}

// uint32 sun_high_angle = 30;
inline void WeatherItem::clear_sun_high_angle() {
  sun_high_angle_ = 0u;
}
inline ::google::protobuf::uint32 WeatherItem::sun_high_angle() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherItem.sun_high_angle)
  return sun_high_angle_;
}
inline void WeatherItem::set_sun_high_angle(::google::protobuf::uint32 value) {
  
  sun_high_angle_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherItem.sun_high_angle)
}

// uint32 sun_orig_angle = 31;
inline void WeatherItem::clear_sun_orig_angle() {
  sun_orig_angle_ = 0u;
}
inline ::google::protobuf::uint32 WeatherItem::sun_orig_angle() const {
  // @@protoc_insertion_point(field_get:NetProto.WeatherItem.sun_orig_angle)
  return sun_orig_angle_;
}
inline void WeatherItem::set_sun_orig_angle(::google::protobuf::uint32 value) {
  
  sun_orig_angle_ = value;
  // @@protoc_insertion_point(field_set:NetProto.WeatherItem.sun_orig_angle)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace NetProto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_weather_5fitem_5f2_5fclient_2eproto__INCLUDED
