#ifndef _PACKAGE_H_
#define _PACKAGE_H_

#define ADDUSERREQ 0
#define ADDUSERRESP 100
#define CHECKUSERREQ 1
#define CHECKUSERRESP 101
#define CHECKUNAMEREQ 2
#define CHECKUNAMERESP 102

#endif /* _PACKAGE_H_ */
